# config file version
apiVersion: 1

# list of grafana datasources to insert/update. This is mapped to the volume in the docker-compose.yaml file
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: test
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'